<?php

/**
 * Admin sidebar page keys → route patterns and default role access.
 * Super admin can override per staff via admin_page_permissions JSON.
 */
return [
    'always_allowed_routes' => [
        'admin.dashboard',
        'admin.logout',
        'admin.profile.*',
        'admin.sidebar-menu-order.*',
    ],

    'pages' => [
        'dashboard' => [
            'label' => 'Dashboard',
            'group' => 'Core',
            'route_patterns' => ['admin.dashboard'],
            'default_roles' => ['super_admin', 'admin', 'staff', 'support', 'wallet_support'],
        ],
        'payments' => [
            'label' => 'Payments',
            'group' => 'Payments',
            'route_patterns' => ['admin.payments.*'],
            'default_roles' => ['super_admin', 'admin', 'staff'],
        ],
        'payments_needs_review' => [
            'label' => 'Needs Review',
            'group' => 'Payments',
            'route_patterns' => ['admin.payments.needs-review'],
            'default_roles' => ['super_admin', 'admin', 'staff'],
        ],
        'businesses' => [
            'label' => 'Businesses',
            'group' => 'Merchants',
            'route_patterns' => ['admin.businesses.*'],
            'default_roles' => ['super_admin', 'admin', 'staff', 'wallet_support'],
        ],
        'support' => [
            'label' => 'Support Tickets',
            'group' => 'Support',
            'route_patterns' => ['admin.support.*'],
            'default_roles' => ['super_admin', 'admin', 'staff', 'support', 'wallet_support'],
        ],
        'virtual_cards' => [
            'label' => 'Card Management',
            'group' => 'Wallet',
            'route_patterns' => ['admin.virtual-cards.*'],
            'default_roles' => ['super_admin', 'admin', 'wallet_support'],
        ],
        'businesses_kyc' => [
            'label' => 'Business KYC',
            'group' => 'KYC',
            'route_patterns' => ['admin.businesses-kyc.*'],
            'default_roles' => ['super_admin', 'admin', 'staff', 'wallet_support'],
        ],
        'renters_kyc' => [
            'label' => 'Renters KYC',
            'group' => 'KYC',
            'route_patterns' => ['admin.renters-kyc.*'],
            'default_roles' => ['super_admin', 'admin', 'staff'],
        ],
        'rentals' => [
            'label' => 'Rentals',
            'group' => 'Rentals',
            'route_patterns' => ['admin.rentals.*', 'admin.rental-categories.*', 'admin.rental-items.*', 'admin.rental-featured-banners.*'],
            'default_roles' => ['super_admin', 'admin', 'staff'],
        ],
        'rentals_app_sessions' => [
            'label' => 'Rentals app sessions',
            'group' => 'Rentals',
            'route_patterns' => ['admin.rentals-app-sessions.*'],
            'default_roles' => ['super_admin', 'admin', 'staff'],
        ],
        'whatsapp_wallet' => [
            'label' => 'WhatsApp wallet',
            'group' => 'Wallet',
            'route_patterns' => ['admin.whatsapp-wallet.index', 'admin.whatsapp-wallet.settings', 'admin.whatsapp-wallet.update', 'admin.whatsapp-wallet.fx-rates.update'],
            'default_roles' => ['super_admin', 'admin', 'wallet_support'],
        ],
        'whatsapp_wallet_users' => [
            'label' => 'Wallet users',
            'group' => 'Wallet',
            'route_patterns' => ['admin.whatsapp-wallet.wallets.*'],
            'default_roles' => ['super_admin', 'admin', 'wallet_support'],
        ],
        'whatsapp_wallet_signup_attempts' => [
            'label' => 'Signup attempts',
            'group' => 'Wallet',
            'route_patterns' => ['admin.whatsapp-wallet.signup-attempts.*'],
            'default_roles' => ['super_admin', 'admin', 'wallet_support'],
        ],
        'app_sessions' => [
            'label' => 'App sessions',
            'group' => 'Wallet',
            'route_patterns' => ['admin.app-sessions.*'],
            'default_roles' => ['super_admin', 'admin', 'wallet_support'],
        ],
        'whatsapp_wallet_transactions' => [
            'label' => 'Wallet transactions',
            'group' => 'Wallet',
            'route_patterns' => ['admin.whatsapp-wallet.transactions.*', 'admin.whatsapp-wallet.money-requests.*', 'admin.whatsapp-wallet.save-together.*'],
            'default_roles' => ['super_admin', 'admin', 'wallet_support'],
        ],
        'business_name_registrations' => [
            'label' => 'Business names',
            'group' => 'Wallet',
            'route_patterns' => ['admin.business-name-registrations.*'],
            'default_roles' => ['super_admin', 'admin'],
        ],
        'business_account_applications' => [
            'label' => 'Business accounts',
            'group' => 'Wallet',
            'route_patterns' => ['admin.business-account-applications.*'],
            'default_roles' => ['super_admin', 'admin'],
        ],
        'withdrawals' => [
            'label' => 'Withdrawals',
            'group' => 'Finance',
            'route_patterns' => ['admin.withdrawals.*'],
            'default_roles' => ['super_admin', 'admin', 'staff'],
        ],
        'overdraft' => [
            'label' => 'Loan & overdraft queue',
            'group' => 'Finance',
            'route_patterns' => ['admin.credit-facility-applications.*', 'admin.overdraft-applications.*'],
            'default_roles' => ['super_admin', 'admin', 'staff'],
        ],
        'business_payroll' => [
            'label' => 'Business payroll',
            'group' => 'Finance',
            'route_patterns' => ['admin.business-payroll.*'],
            'default_roles' => ['super_admin', 'admin', 'wallet_support'],
        ],
        'peer_lending_offers' => [
            'label' => 'Peer lending offers',
            'group' => 'Finance',
            'route_patterns' => ['admin.peer-lending.offers.*'],
            'default_roles' => ['super_admin'],
        ],
        'peer_lending_loans' => [
            'label' => 'Peer loan queue',
            'group' => 'Finance',
            'route_patterns' => ['admin.peer-lending.loans.*'],
            'default_roles' => ['super_admin'],
        ],
        'external_apis' => [
            'label' => 'External APIs',
            'group' => 'System',
            'route_patterns' => ['admin.external-apis.*'],
            'default_roles' => ['super_admin', 'admin'],
        ],
        'processed_emails' => [
            'label' => 'Inbox',
            'group' => 'System',
            'route_patterns' => ['admin.processed-emails.*'],
            'default_roles' => ['super_admin', 'admin', 'staff'],
        ],
        'transaction_logs' => [
            'label' => 'Transaction Logs',
            'group' => 'System',
            'route_patterns' => ['admin.transaction-logs.*'],
            'default_roles' => ['super_admin', 'admin', 'staff'],
        ],
        'api_hits' => [
            'label' => 'API hits',
            'group' => 'System',
            'route_patterns' => ['admin.api-hits.*'],
            'default_roles' => ['super_admin', 'admin', 'staff'],
        ],
        'audits' => [
            'label' => 'Audits',
            'group' => 'System',
            'route_patterns' => ['admin.audits.*'],
            'default_roles' => ['super_admin', 'admin'],
        ],
        'mevon_balance_monitor' => [
            'label' => 'Mevon Balance Monitor',
            'group' => 'System',
            'route_patterns' => ['admin.audits.mevonpay.monitor*'],
            'default_roles' => ['super_admin', 'admin'],
        ],
        'honeypot' => [
            'label' => 'Honeypot',
            'group' => 'System',
            'route_patterns' => ['admin.honeypot.*'],
            'default_roles' => ['super_admin', 'admin'],
        ],
        'match_attempts' => [
            'label' => 'Match Logs',
            'group' => 'System',
            'route_patterns' => ['admin.match-attempts.*'],
            'default_roles' => ['super_admin', 'admin', 'staff'],
        ],
        'invoices' => [
            'label' => 'Invoices',
            'group' => 'System',
            'route_patterns' => ['admin.invoices.*'],
            'default_roles' => ['super_admin', 'admin', 'staff'],
        ],
        'payment_links' => [
            'label' => 'Payment links',
            'group' => 'System',
            'route_patterns' => ['admin.payment-links.*'],
            'default_roles' => ['super_admin', 'admin', 'staff'],
        ],
        'email_accounts' => [
            'label' => 'Email Accounts',
            'group' => 'System',
            'route_patterns' => ['admin.email-accounts.*'],
            'default_roles' => ['super_admin', 'admin'],
        ],
        'account_numbers' => [
            'label' => 'Account Numbers',
            'group' => 'System',
            'route_patterns' => ['admin.account-numbers.*'],
            'default_roles' => ['super_admin', 'admin'],
        ],
        'bank_email_templates' => [
            'label' => 'Bank Templates',
            'group' => 'System',
            'route_patterns' => ['admin.bank-email-templates.*'],
            'default_roles' => ['super_admin', 'admin', 'staff'],
        ],
        'bank_logos' => [
            'label' => 'Bank Logos',
            'group' => 'System',
            'route_patterns' => ['admin.bank-logos.*'],
            'default_roles' => ['super_admin', 'admin'],
        ],
        'bank_account_prefixes' => [
            'label' => 'Bank account prefixes',
            'group' => 'Wallet',
            'route_patterns' => ['admin.bank-account-prefixes.*'],
            'default_roles' => ['super_admin', 'admin', 'wallet_support'],
        ],
        'test_transaction' => [
            'label' => 'Test Transaction',
            'group' => 'System',
            'route_patterns' => ['admin.test-transaction.*'],
            'default_roles' => ['super_admin', 'admin', 'staff'],
        ],
        'renters' => [
            'label' => 'Rental users',
            'group' => 'Rentals',
            'route_patterns' => ['admin.renters.*'],
            'default_roles' => ['super_admin', 'admin', 'staff'],
        ],
        'tickets' => [
            'label' => 'Tickets',
            'group' => 'Events',
            'route_patterns' => ['admin.tickets.events.*', 'admin.tickets.orders.*'],
            'default_roles' => ['super_admin', 'admin', 'staff'],
        ],
        'tickets_scanner' => [
            'label' => 'QR Scanner',
            'group' => 'Events',
            'route_patterns' => ['admin.tickets.scanner', 'admin.tickets.scanner*'],
            'default_roles' => ['super_admin', 'admin', 'staff'],
        ],
        'charity' => [
            'label' => 'Go Fund',
            'group' => 'Events',
            'route_patterns' => ['admin.charity.*'],
            'default_roles' => ['super_admin', 'admin', 'staff'],
        ],
        'memberships' => [
            'label' => 'Memberships',
            'group' => 'Events',
            'route_patterns' => ['admin.memberships.*', 'admin.membership-categories.*'],
            'default_roles' => ['super_admin', 'admin', 'staff'],
        ],
        'developer_program' => [
            'label' => 'Developer program',
            'group' => 'System',
            'route_patterns' => ['admin.developer-program.*'],
            'default_roles' => ['super_admin', 'admin', 'staff'],
        ],
        'investor_pitch_access' => [
            'label' => 'Investor pitch access',
            'group' => 'System',
            'route_patterns' => ['admin.investor-pitch-access.*'],
            'default_roles' => ['super_admin'],
        ],
        'desktop_telemetry' => [
            'label' => 'Desktop DRM',
            'group' => 'System',
            'route_patterns' => ['admin.desktop-telemetry.*'],
            'default_roles' => ['super_admin'],
        ],
        'whitelisted_emails' => [
            'label' => 'Whitelisted Emails',
            'group' => 'System',
            'route_patterns' => ['admin.whitelisted-emails.*'],
            'default_roles' => ['super_admin', 'admin'],
        ],
        'pages' => [
            'label' => 'Pages',
            'group' => 'System',
            'route_patterns' => ['admin.pages.*'],
            'default_roles' => ['super_admin', 'admin'],
        ],
        'announcements' => [
            'label' => 'Announcements',
            'group' => 'System',
            'route_patterns' => ['admin.announcements.*'],
            'default_roles' => ['super_admin', 'admin'],
        ],
        'settings' => [
            'label' => 'Settings',
            'group' => 'System',
            'route_patterns' => ['admin.settings.*'],
            'default_roles' => ['super_admin', 'admin'],
        ],
        'email_templates' => [
            'label' => 'Email Templates',
            'group' => 'System',
            'route_patterns' => ['admin.email-templates.*'],
            'default_roles' => ['super_admin', 'admin'],
        ],
        'staff' => [
            'label' => 'Staff Management',
            'group' => 'System',
            'route_patterns' => ['admin.staff.*'],
            'default_roles' => ['super_admin'],
        ],
    ],
];
